<?php

namespace Models\Lists;

use Bitrix\Main\Entity\ReferenceField;
use Models\AbstractIblockPropertyValuesTable;

class DoctorsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 19;

    public static function getMap(): array
    {
        $map = [
            'PROCEDURES' => new ReferenceField(
                'PROCEDURES',
                ProcsPropertyValuesTable::class,
                ['=this.PROCEDUR_MULTI' => 'ref.IBLOCK_ELEMENT_ID']
            )
        ];

        return parent::getMap() + $map; // TODO: Change the autogenerated stub

    }
}